### ISSUE TITLE
Search box focus

### ISSUE THREAD

**Issue by nathancashmoredwp** [lm-tools/digital-resource-library#34]
More of a requirement than issue but think it would help if on the Search page you should always have focus in the search box when the page loads.

**Comment by jessstubenbord** [comment]
This could be done with the html autofocus attribute but this raises questions of accessibility and expected use.

Autofocusing on the search box could make sense since the primary function of the page currently is searching, and there is not much on the page before this which we would expect people to focus on.

Browser support for autofocus:
https://caniuse.com/#feat=autofocus
